services:

  kafka:
    image: quay.io/debezium/kafka:3.5
    container_name: shadowbase-kafka

    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"

    environment:
      CLUSTER_ID: "oh-sxaDRTcyAr6pFRbXyzA"
      NODE_ID: "1"
      NODE_ROLE: "combined"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"

      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:29092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"


  production-db:
    image: postgres:16
    container_name: shadowbase-production-db

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productiondb

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=10
      - -c
      - max_wal_senders=10


  connect:
    image: quay.io/debezium/connect:3.5
    container_name: shadowbase-debezium

    ports:
      - "8083:8083"

    depends_on:
      - kafka
      - production-db

    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"

      CONFIG_STORAGE_TOPIC: shadowbase_connect_configs
      OFFSET_STORAGE_TOPIC: shadowbase_connect_offsets
      STATUS_STORAGE_TOPIC: shadowbase_connect_statuses