spring.application.name=shadowbase-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/shadowbase
spring.datasource.username=shadowbase
spring.datasource.password=shadowbase123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=shadowbase-replayer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer